version: 2
updates:

  - package-ecosystem: "npm" 
    directory: "/00-Starter-Seed" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
      
  - package-ecosystem: "npm" 
    directory: "/01-Login" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
